import { IUserAdminInfo } from "./models";

export function GET_MOCK_EMPLOYEES_INFO(id: number): IUserAdminInfo {
    return {
        meta: {
            pagination: {
                total: 1566,
                pages: 79,
                page: 1,
                limit: 20,
            },
        },
        data: [
            {
                id: 1,
                name: "Elnur",
                surname: "Dure314@gmail.com",
                dateOfBirth: "2008-11-11",
                position: "Backend Developer",
                phoneNumber: "+994502345598",
            },
            {
                id: 2,
                name: "Orkhan",
                surname: "Dure314@gmail.com",
                dateOfBirth: "2008-11-11",
                position: "Backend Developer",
                phoneNumber: "+994502345598",
            },
            {
                id: 3,
                name: "Seymur",
                surname: "Dure314@gmail.com",
                dateOfBirth: "2008-11-11",
                position: "Backend Developer",
                phoneNumber: "+994502345598",
            },
            {
                id: 4,
                name: "Maryam",
                surname: "Dure314@gmail.com",
                dateOfBirth: "2000-01-11",
                position: "Designer",
                phoneNumber: "+994502005090",
            },
            {
                id: 5,
                name: "Vusal",
                surname: "Dure314@gmail.com",
                dateOfBirth: "2008-11-11",
                position: "Backend Developer",
                phoneNumber: "+994502345598",
            },
            {
                id: 6,
                name: "Elnur",
                surname: "Dure314@gmail.com",
                dateOfBirth: "2008-11-11",
                position: "Backend Developer",
                phoneNumber: "+994502345598",
            },
            {
                id: 7,
                name: "Elnur",
                surname: "Dure314@gmail.com",
                dateOfBirth: "2008-11-11",
                position: "Backend Developer",
                phoneNumber: "+994502345598",
            },
            {
                id: 8,
                name: "Elnur",
                surname: "Dure314@gmail.com",
                dateOfBirth: "2008-11-11",
                position: "Backend Developer",
                phoneNumber: "+994502345598",
            },
            {
                id: 9,
                name: "Elnur",
                surname: "Dure314@gmail.com",
                dateOfBirth: "2008-11-11",
                position: "Backend Developer",
                phoneNumber: "+994502345598",
            },
            {
                id: 10,
                name: "Elnur",
                surname: "Dure314@gmail.com",
                dateOfBirth: "2008-11-11",
                position: "Backend Developer",
                phoneNumber: "+994502345598",
            },
            {
                id: 11,
                name: "Elnur",
                surname: "Dure314@gmail.com",
                dateOfBirth: "2008-11-11",
                position: "Backend Developer",
                phoneNumber: "+994502345598",
            },
            {
                id: 12,
                name: "Elnur",
                surname: "Dure314@gmail.com",
                dateOfBirth: "2008-11-11",
                position: "Backend Developer",
                phoneNumber: "+994502345598",
            },
            {
                id: 13,
                name: "Elnur",
                surname: "Dure314@gmail.com",
                dateOfBirth: "2008-11-11",
                position: "Backend Developer",
                phoneNumber: "+994502345598",
            },
            {
                id: 14,
                name: "Elnur",
                surname: "Dure314@gmail.com",
                dateOfBirth: "2008-11-11",
                position: "Backend Developer",
                phoneNumber: "+994502345598",
            },
            {
                id: 15,
                name: "Elnur",
                surname: "Dure314@gmail.com",
                dateOfBirth: "2008-11-11",
                position: "Backend Developer",
                phoneNumber: "+994502345598",
            },
            {
                id: 16,
                name: "Elnur",
                surname: "Dure314@gmail.com",
                dateOfBirth: "2008-11-11",
                position: "Backend Developer",
                phoneNumber: "+994502345598",
            },
        ],
    };
}
