import { IUserAdminInfo } from "./models";

export const MOCK_EMPLOYEES: IUserAdminInfo = {
    pagination: {
        total: 43,
        pages: 5,
        page: 1,
        limit: 10,
    },
    data: [
        {
            id: 1,
            name: "Elnur",
            surname: "Alizade",
            dateOfBirth: "2000-06-05",
            position: "Backend Developer",
            phoneNumber: "+994502345598",
        },
        {
            id: 2,
            name: "Orkhan",
            surname: "Salimov",
            dateOfBirth: "1996-09-05",
            position: "Frontend Developer",
            phoneNumber: "+994502345598",
        },
        {
            id: 3,
            name: "Seymur",
            surname: "Alizade",
            dateOfBirth: "1995-11-11",
            position: "DevOps",
            phoneNumber: "+994502345598",
        },
        {
            id: 4,
            name: "Maryam",
            surname: "Alizade",
            dateOfBirth: "1997-01-11",
            position: "Designer",
            phoneNumber: "+994502005090",
        },
        {
            id: 5,
            name: "Vusal",
            surname: "Huseynli",
            dateOfBirth: "1990-11-11",
            position: "Tester",
            phoneNumber: "+994502345598",
        },
        {
            id: 6,
            name: "Elnur",
            surname: "Alizade",
            dateOfBirth: "2008-11-11",
            position: "Backend Developer",
            phoneNumber: "+994502345598",
        },
        {
            id: 7,
            name: "Farxad",
            surname: "Huseynli",
            dateOfBirth: "2008-10-07",
            position: "Manager",
            phoneNumber: "+994502345598",
        },
        {
            id: 8,
            name: "Elnara",
            surname: "Alizade",
            dateOfBirth: "2008-11-09",
            position: "BI",
            phoneNumber: "+994502345598",
        },
        {
            id: 9,
            name: "Aytan",
            surname: "Alizade",
            dateOfBirth: "1998-02-11",
            position: "Tester",
            phoneNumber: "+994502345598",
        },
        {
            id: 10,
            name: "Jeyhun",
            surname: "Huseynli",
            dateOfBirth: "2008-11-11",
            position: "Backend Developer",
            phoneNumber: "+994502345598",
        },
        {
            id: 11,
            name: "Ruslan",
            surname: "Alizade",
            dateOfBirth: "2008-11-11",
            position: "Backend Developer",
            phoneNumber: "+994502345598",
        },
        {
            id: 12,
            name: "Elnur",
            surname: "Huseynli",
            dateOfBirth: "2008-11-11",
            position: "Backend Developer",
            phoneNumber: "+994502345598",
        },
        {
            id: 13,
            name: "Aytan",
            surname: "Alizade",
            dateOfBirth: "1998-02-11",
            position: "Tester",
            phoneNumber: "+994502345598",
        },
        {
            id: 14,
            name: "Elnur",
            surname: "Alizade",
            dateOfBirth: "2008-11-11",
            position: "Backend Developer",
            phoneNumber: "+994502345598",
        },
        {
            id: 15,
            name: "Elnara",
            surname: "Alizade",
            dateOfBirth: "2008-11-09",
            position: "BI",
            phoneNumber: "+994502345598",
        },
        {
            id: 16,
            name: "Vusal",
            surname: "Alizade",
            dateOfBirth: "1990-11-11",
            position: "Tester",
            phoneNumber: "+994502345598",
        },
        {
            id: 17,
            name: "Seymur",
            surname: "Alizade",
            dateOfBirth: "1995-11-11",
            position: "DevOps",
            phoneNumber: "+994502345598",
        },
        {
            id: 18,
            name: "Aytan",
            surname: "Alizade",
            dateOfBirth: "1998-02-11",
            position: "Tester",
            phoneNumber: "+994502345598",
        },
        {
            id: 19,
            name: "Elnur",
            surname: "Alizade",
            dateOfBirth: "2008-11-11",
            position: "Backend Developer",
            phoneNumber: "+994502345598",
        },
        {
            id: 20,
            name: "Elnur",
            surname: "Alizade",
            dateOfBirth: "2008-11-11",
            position: "Backend Developer",
            phoneNumber: "+994502345598",
        },
        {
            id: 21,
            name: "Elnur",
            surname: "Alizade",
            dateOfBirth: "2008-11-11",
            position: "Backend Developer",
            phoneNumber: "+994502345598",
        },
        {
            id: 22,
            name: "Elnur",
            surname: "Alizade",
            dateOfBirth: "2008-11-11",
            position: "Backend Developer",
            phoneNumber: "+994502345598",
        },
        {
            id: 23,
            name: "Elnara",
            surname: "Alizade",
            dateOfBirth: "2008-11-09",
            position: "BI",
            phoneNumber: "+994502345598",
        },
        {
            id: 24,
            name: "Aytan",
            surname: "Alizade",
            dateOfBirth: "1998-02-11",
            position: "Tester",
            phoneNumber: "+994502345598",
        },
        {
            id: 25,
            name: "Vusal",
            surname: "Huseynli",
            dateOfBirth: "1990-11-11",
            position: "Tester",
            phoneNumber: "+994502345598",
        },
        {
            id: 26,
            name: "Orkhan",
            surname: "Alizade",
            dateOfBirth: "1996-09-05",
            position: "Frontend Developer",
            phoneNumber: "+994502345598",
        },
        {
            id: 27,
            name: "Elnur",
            surname: "Alizade",
            dateOfBirth: "2008-11-11",
            position: "Backend Developer",
            phoneNumber: "+994502345598",
        },
        {
            id: 28,
            name: "Elnara",
            surname: "Alizade",
            dateOfBirth: "2008-11-09",
            position: "BI",
            phoneNumber: "+994502345598",
        },
        {
            id: 29,
            name: "Aytan",
            surname: "Alizade",
            dateOfBirth: "1998-02-11",
            position: "Tester",
            phoneNumber: "+994502345598",
        },
        {
            id: 30,
            name: "Seymur",
            surname: "Alizade",
            dateOfBirth: "1995-11-11",
            position: "DevOps",
            phoneNumber: "+994502345598",
        },
        {
            id: 31,
            name: "Elnur",
            surname: "Alizade",
            dateOfBirth: "2008-11-11",
            position: "Backend Developer",
            phoneNumber: "+994502345598",
        },
        {
            id: 32,
            name: "Elnur",
            surname: "Alizade",
            dateOfBirth: "2008-11-11",
            position: "Backend Developer",
            phoneNumber: "+994502345598",
        },
        {
            id: 33,
            name: "Vusal",
            surname: "Alizade",
            dateOfBirth: "1990-11-11",
            position: "Tester",
            phoneNumber: "+994502345598",
        },
        {
            id: 34,
            name: "Aytan",
            surname: "Alizade",
            dateOfBirth: "1998-02-11",
            position: "Tester",
            phoneNumber: "+994502345598",
        },
        {
            id: 35,
            name: "Elnur",
            surname: "Huseynli",
            dateOfBirth: "2008-11-11",
            position: "Backend Developer",
            phoneNumber: "+994502345598",
        },
        {
            id: 36,
            name: "Elnur",
            surname: "Alizade",
            dateOfBirth: "2008-11-11",
            position: "Backend Developer",
            phoneNumber: "+994502345598",
        },
        {
            id: 37,
            name: "Elnara",
            surname: "Alizade",
            dateOfBirth: "2008-11-09",
            position: "BI",
            phoneNumber: "+994502345598",
        },
        {
            id: 38,
            name: "Elnur",
            surname: "Alizade",
            dateOfBirth: "2008-11-11",
            position: "Backend Developer",
            phoneNumber: "+994502345598",
        },
        {
            id: 39,
            name: "Orkhan",
            surname: "Alizade",
            dateOfBirth: "1996-09-05",
            position: "Frontend Developer",
            phoneNumber: "+994502345598",
        },
        {
            id: 40,
            name: "Seymur",
            surname: "Alizade",
            dateOfBirth: "1995-11-11",
            position: "DevOps",
            phoneNumber: "+994502345598",
        },
        {
            id: 41,
            name: "Vusal",
            surname: "Alizade",
            dateOfBirth: "1990-11-11",
            position: "Tester",
            phoneNumber: "+994502345598",
        },
        {
            id: 42,
            name: "Aytan",
            surname: "Huseynli",
            dateOfBirth: "1998-02-11",
            position: "Tester",
            phoneNumber: "+994502345598",
        },
        {
            id: 43,
            name: "Orkhan",
            surname: "Alizade",
            dateOfBirth: "1996-09-05",
            position: "Frontend Developer",
            phoneNumber: "+994502345598",
        },
    ],
};
